### ISSUE TITLE
Lack of alive messages?

### ISSUE THREAD

**Issue by raffael** [fajran/tongseng#2]
Is it possible that some TUIO alive messages are not sent by TongSeng as the TUIO protocol specifies?

When performing longer lasting drag gestures on the Magic TrackPad, I get a quick 'remove, start' sequence every second or so:

MOVE
MOVE
...
MOVE
MOVE
REMOVE
START
MOVE
MOVE
...

It might be possible that this remove-start sequence is not triggered by TongSeng, but by a different object in my chain from TUIO server to browser. But I really think the mistake is in TongSeng.
Anyway, I'm so thankful for TongSeng, we're working with it while developing apps for Multitouch enabled Tables.

**Comment by mkalten** [comment]
tongseng uses the mainline TUIO C++ library, which correctly implements the TUIO11 protocal ...
